# Numpy Arrays

Arrays come as one dimensional vetor or two dimensional matrices

In [3]:
my_list = [1, 2, 3]

In [4]:
import numpy as np

In [5]:
np.array(my_list)

array([1, 2, 3])

#### Transform my_list into an array

In [6]:
arr = np.array(my_list) #assign

In [7]:
arr

array([1, 2, 3])

#### If I want a matrix, I can cast a list of lists

In [8]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---

### Built-in methods

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# I can add a new parameter called step size ==> I want all even numbers from 0 to 10
np.arange(start = 0, stop = 11, step = 2)

array([ 0,  2,  4,  6,  8, 10])

### Zeros and Ones

In [12]:
np.zeros(3)  # vetor of zeros

array([0., 0., 0.])

In [13]:
np.zeros((2,3))  # pass a tuple(nr_rows, nr_columns) to get a matriz of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace

In [15]:
np.linspace(start = 0, stop = 5, num = 50)

# Return 1 dimensional vetor with 10 evenly space points

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

## Identity Matrix -- Eye

In [16]:
## Create an Identity Matrix ## 

np.eye(4)

# The parameter is the diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random Matrices

In [17]:
np.random.rand(5) # one dimensional array populated with random samples from a uniform distribution over 0 to 1

array([0.59856836, 0.10951444, 0.20576895, 0.16907949, 0.33301223])

In [18]:
np.random.rand(5, 5) # two dimensional array 

array([[0.13649281, 0.3911875 , 0.88429396, 0.74278955, 0.0445139 ],
       [0.74620629, 0.95670332, 0.82647534, 0.34254076, 0.17608999],
       [0.02473499, 0.13893648, 0.72448047, 0.27854641, 0.33219923],
       [0.49580768, 0.72677006, 0.83500932, 0.534038  , 0.83489962],
       [0.23847422, 0.25744126, 0.7718832 , 0.83139704, 0.10829285]])

In [19]:
# Return numbers form a standard normal distribution around 0 (gaussian)
np.random.randn(2)

array([0.00361032, 1.83161436])

In [20]:
np.random.randn(3,4) # two dimensional matrix

array([[-0.4193271 ,  0.53380724,  0.64705928,  0.73586537],
       [ 0.08227876,  1.65141614,  0.48190845, -1.13962161],
       [ 0.19092692,  1.07919045,  1.294179  ,  0.06427179]])

In [21]:
np.random.randint(1,100, 10)  # Returns random integers from a low (inclusive) to a high number (exclusive). 
                              #I can state how many numbers I want in ther 3rd argument 

array([82, 63, 80, 81,  4, 63, 31, 27, 34, 95])

## Array Attributes and Methods

In [25]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([30, 45, 47,  0,  6, 41, 38,  8, 42,  2])

##### reshape method == return the array that contains the same data but in a new shape

Pass in the number of rows and columns in the parameters.

Rows * Columns must be equal to the actual number of elements

In [27]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

##### rmax and min methods | argmax and argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [28]:
ranarr

array([30, 45, 47,  0,  6, 41, 38,  8, 42,  2])

In [31]:
ranarr.max()

47

In [32]:
ranarr.min()

0

In [33]:
ranarr.argmax()

2

In [34]:
ranarr.argmin()

3

## Shape

Shape is an attribute that arrays have (not a method):

In [37]:
arr.shape

# Indicates that arr was a one dimensional vector

(25,)

In [40]:
arr = arr.reshape(5, 5)

In [41]:
arr.shape

# Now is a two dimensional matrix 5 by 5

(5, 5)

### dtype

You can also grab the data type of the object in the array:

In [42]:
arr.dtype

dtype('int32')