# NumPy Indexing and Selection


In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [5]:
# Get a value at an index
arr[8]

8

In [7]:
# Get value in range [inclusive:exclusive]
arr[1:5] 

array([1, 2, 3, 4])

In [9]:
# Slicing! # arr[0:5] is the same as:
arr[:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [13]:
arr[0:5] = 100 
arr

# replace the values in the array by 100

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
# reset
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
#Important notes on Slices
slice_of_arr = arr[0:6]

In [18]:
# Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
#change slice
slice_of_arr[:] = 99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [21]:
# Now note the changes also occur in our original array!

arr

# Data is not copied, it's a view of the original array! This avoids memory problems!

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#### copy method

In [22]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

---

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [24]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

##### comma single bracket notation

In [26]:
# I want to grab the digit 5

# For double bracket notation, I first pass the row I want and then the column
arr_2d[0][0]

5

In [27]:
arr_2d[0,0]

5

##### slice notation == I want to grab a chunk of my matrix

In [29]:
arr_2d[:2, 1:]

# Slice the rows from 0 to 1 (exclude 2)
# Slice the columns from 1 to the end

array([[10, 15],
       [25, 30]])

In [30]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [31]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order

In [36]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
#Length of array
arr_length = arr2d.shape[1]
arr_length

10

In [38]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [42]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [43]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

---

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [45]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Now I can use this boolean array to do some conditional selection

In [50]:
# I only get the results when the boolean is True
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [51]:
# This can be done in one step by passing the condition
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [52]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [54]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])