In [1]:
l = [2345, 27, 546, 215, -1234]

In [2]:
l

[2345, 27, 546, 215, -1234]

In [3]:
import numpy as np

In [6]:
a = np.array (l)  #criar uma array, neste caso converter a lista numa array (dar um nome, neste caso "a")

In [7]:
a

array([ 2345,    27,   546,   215, -1234])

In [8]:
#não se pode ter uma array de diferentes tipos de variáveis. É como um vetor em R

#podemos ir buscar funções específicas a listas e a arrays, sendo que a arrays têm mais variedade. 

#l.pop retira um elemento da lista...   #a.mean calcula a média da array

#matrizes são arrays de duas dimensões, logo melhor trabalhar com esse tipo

In [9]:
a.max ()

2345

In [12]:
a.argmax()

0

In [13]:
a.byteswap()

array([ 688455680,  452984832,  570556416, -687865856,  788267007])

In [14]:
a

array([ 2345,    27,   546,   215, -1234])

---

In [15]:
l

[2345, 27, 546, 215, -1234]

In [16]:
l[1:]

[27, 546, 215, -1234]

In [17]:
l[0:1:2]

[2345]

In [18]:
l[::2]

[2345, 546, -1234]

In [19]:
a

array([ 2345,    27,   546,   215, -1234])

In [20]:
a[2:]

array([  546,   215, -1234])

In [21]:
a[2:4]

array([546, 215])

In [22]:
#quando cortas (slice) uma array, não estás a fazer uma cópia da mesma. Ao contrário das listas

In [23]:
b = a[2:4]

In [24]:
b

array([546, 215])

In [25]:
b[0]

546

In [26]:
b[:] = 111  #substituir os elementos da array b por 111

In [27]:
b

array([111, 111])

In [28]:
a

array([ 2345,    27,   111,   111, -1234])

In [30]:
#por causa da troca na linha 26, os elementos de a foram substituídos. Então, slice an array é criar uma 
#vista mais estreita da array original

In [31]:
c = a.copy()

In [32]:
c

array([ 2345,    27,   111,   111, -1234])

In [33]:
c[0]=0

In [34]:
c

array([    0,    27,   111,   111, -1234])

In [35]:
a

array([ 2345,    27,   111,   111, -1234])